spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:log4jdbc:mysql://localhost:3306/multi_module
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  type-aliases-package: com.multi.*.bean
  configuration:
    map-underscore-to-camel-case: true

